---
title: "International Merchandise Trade Statistics Highlights"
author: Christophe Bontemps (SIAP)^[Based on data and information from Vanuatu National
  Statistical Office (VNSO) ]
subtitle: '*A simple report*'
date: "2024-01-31"
output:
  pdf_document:
    df_print: kable
    toc: yes
    keep_tex: yes
    fig_width: 6.5
    fig_height: 4
    extra_dependencies: float
  word_document:
    toc: yes
  html_document:
    df_print: paged
    toc: yes
    keep_md: yes
    code_folding: show
    fig_width: 6.5
    fig_height: 4
---


```{r setup, include=FALSE}
# Set echo=FALSE as default for code cells
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      dpi = 600)
# My colors:
SIAP.color <- "#0385a8"
```



```{r libraries, include = FALSE}
#### Preparation ####

# Load the required libraries
library(dplyr) # Manipulating data
library(stringr) # common string operations
library(tidyverse) # Manipulating data

# For tables 
# library(kableExtra)
# library(modelsummary)
# library(gt) 
# library(gtsummary)
# library(tinytable)


library(flextable)

```


# Loading the data

```{r}
Mydata <- read.csv("Data/TradeData.csv")
```


# Statistics
Now let's look at our constructed data set and start exploring: 
```{r}
head(Mydata)
```
... and let's have some **descriptive statistics**
```{r}
#datasummary_skim(Mydata, type = "numeric")
```



## Main Exports over the whole period

### As a table

```{r  }
# Calculate total statistical value by principle export type
CommodityByType <- Mydata %>%
  group_by(Principle_Exports) %>%
  summarise(total = sum(Stat_Value)) %>%
  arrange(desc(total))

# kable(CommodityByType, caption = "Exports from Vanuatu [ 2000-2010].") %>%
#   kable_styling()

```

```{r}
# To reduce the homogenization efforts and the number of functions to be called, 
# it is recommended to define formatting properties once and for all

set_flextable_defaults(
  font.size = 10,   table.layout = "autofit")


flextable(CommodityByType)


```

 Or as a graphic: 

```{r }
# Plot the exports
CommodityByType  %>%
  ggplot(aes(x = reorder(Principle_Exports, total), y = (total/1000000))) +
    geom_bar(stat = "identity", color="black", fill= "lightsteelblue1", position=position_dodge()) +
      labs( x= "Exports categories", y = "Vatu (millions)") +
  ggtitle(label = " Exports from Vanuatu [ 2000-2010] ",
          subtitle = "Vanuatu National Statistical Office")+
  coord_flip() +
  theme_minimal()

```



```{r EXIT}
knitr::knit_exit()
```



##  Selection of the Year

Imagine now the same report but for any year $ \in [2000, 2010]$

```{r}
MyYear <- 2003
```

| we have selected the year **`r MyYear`** let's see the report!


### As a table

```{r  }
# Now only for a specific year
CommodityByType_Year <- Mydata %>%
  filter(Year == MyYear) %>%
  group_by(Principle.Exports) %>%
  summarise(total = sum(Stat..Value)) %>%
  arrange(desc(total))

kable(CommodityByType_Year,
      caption = paste("Exports from Vanuatu, year = ", MyYear)) %>% 
  kable_styling()



```


 Or as a graphic: 

```{r }

# Plot the exports for the specific year
CommodityByType_Year  %>%
  ggplot(aes(x = reorder(Principle.Exports, total), y = (total/1000000))) +  
    geom_bar(stat = "identity", color="white", fill= SIAP.color, position=position_dodge()) +
      labs( x= "Exports categories", y = "Vatu (millions)") +
  ggtitle(label = paste("Exports from Vanuatu, year = ", MyYear),
          subtitle = "Vanuatu National Statistical Office")+
  coord_flip() +
  theme_minimal()

```






